version: '3.8'

services:
  fraud-detection-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DATASET_URL=${DATASET_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FILE_KEY=${S3_FILE_KEY}
    volumes:
      - ./data:/app/data  # Optional: for local data mounting
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fraud-detection-app
    restart: unless-stopped
